### ISSUE TITLE
When can the code be published? Thank you.

### ISSUE THREAD

**Issue by wellzhi** [Lyz1213/BadEdit#1]
When can the code be published? Thank you.

**Comment by Lyz1213** [comment]
Thanks for your interest, we have already released the code.

**Comment by wellzhi** [comment]
Thank you for your reply. I see that you used an 80G A100 graphics card in this paper, and I just have 4 V100 32G graphics cards. Does my hardware configuration support it?

**Comment by Lyz1213** [comment]
I believe it's sufficient for editing GPT-2 XL. I'm not certain about larger models like LLAMA2, but you can give it a try.
